import items, locations, verbs, scripts, game, dialogue
def Item(item): return items.Get(item)
def Location(location): return locations.Get(location)
def Verb(verb): return verbs.Get(verb)
def Game(): return game.Settings()

verbs.New("sys_talk", "{dialogue.Talk()}")
verbs.New("sys_stats", "{scripts.Stats()}")
verbs.New("sys_jump", "{Item('me').Location(Game().Current('object'))}")

verbs.New(["up", "u"], "{scripts.Go('u')}")
verbs.New(["down", "d"], "{scripts.Go('d')}")

verbs.New(["north", "n"], "{scripts.Go('n')}")
verbs.New(["south", "s"], "{scripts.Go('s')}")
verbs.New(["east", "e"], "{scripts.Go('e')}")
verbs.New(["west", "w"], "{scripts.Go('w')}")

verbs.New(["out", "exit"], "{scripts.Go('o')}")
verbs.New(["in", "enter"], "{scripts.Go('i')}")

verbs.New(["attack", "fight", "hit", "punch", "kick", "break", "strike", "scrape"], "You can't attack that.", "Attack what?")
verbs.New("blow", "You're like your own little wind machine. There's not much of an effect, though.", "Blow on what?")
verbs.New(["burn", "light"], "You can't burn that.", "Burn what?", "What do you want to burn it with?")
verbs.New("close", "You can't close that.", "Close what?")
verbs.New("cross", "You can't cross that.", "What do you want to cross?")
verbs.New(["cut", "chop"], "You can't cut that.", "Cut what?", "What do you want to cut it with?")
verbs.New("dance", "What, like a little jig? You don't think so.")
verbs.New("dig", "You can't dig here.")
verbs.New("drink", "You can't drink that.", "Drink what?")
verbs.New("drop", "You can't drop that.", "Drop what?")
verbs.New(["eat", "bite", "chew"], "You can't eat that.", "What do you want to eat?")
verbs.New("fix", "You're not sure how to fix that.")
verbs.New("fly", "As enticing as that sounds, it doesn't really seem possible.")
verbs.New("feed", "I'm not sure how to feed that.", "Feed what?", "To what?")
verbs.New(["get", "take", "pick", "grab"], "You can't get that.", "Get what?")
verbs.New(["give", "trade"], "You can't give that away.", "Give what?", "To whom?")
verbs.New(["go", "run", "walk", "continue", "forward", "climb", "crawl", "head"], "{scripts.Go()}")
verbs.New("help", """To play the game, simply describe what you'd like to do. You can 'look' to see what's around you, 'take' or 'examine' things you see around you, 'talk' to people, 'climb' a tree, or 'attack' a wombat. Just don't be surprised if the wombat fights back.\n
	To move around, type the compass direction you'd like to travel in, such as 'north' or 'east'. If you want to be really efficient, you can just type the first letter of the word (like 'n' for 'north').\n
	If you'd like to know what items you're carrying, try typing 'look at myself' or 'inventory'.""")
verbs.New("hint", "{Verb('help').DefaultResponse()}")
verbs.New(["inventory", "i"], "{scripts.ShowInventory()}")
verbs.New("jump", "Now's not the time for jumping.")
verbs.New("kiss", "Yeah, that's not too likely.")
verbs.New("knock", "There's no answer.", "Knock on what?")
verbs.New("light", "You can't light that.", "Light what?", "With what?")
verbs.New("listen", "{scripts.Listen()}")
verbs.New("lock", "You can't lock that.", "Lock what?")
verbs.New(["look", "x", "l", "examine", "search", "read"], "{scripts.Look()}")
verbs.New("move", "You can't move that.")
verbs.New("open", "You can't open that.", "Open what?")
verbs.New(["paddle", "stroke"], "It doesn't get you anywhere.")
verbs.New("pour", "You can't pour that.")
verbs.New("pull", "You can't pull that.", "Pull what?")
verbs.New("push", "You can't push that.")
verbs.New(["put", "hang", "place"], "I'm not sure how to put that there.", "Put what?", "Put it where?")
verbs.New("read", "You can't read that.")
verbs.New("shake", "You can't shake that.")
verbs.New("sit", "You're fine the way you are.")
verbs.New("smell", "{scripts.Smell()}")
verbs.New("sorry", "That's okay.")
verbs.New("stop", "You're not sure how to stop that.")
verbs.New("swim", "You can't do that.")
verbs.New(["talk", "say", "ask", "tell"], "You can't think of anything to say.")
verbs.New(["throw", "toss"], "That doesn't seem wise.")
verbs.New(["touch", "poke"], "You can't touch that.")
verbs.New("turn", "You can't turn that.")
verbs.New("unlock", "You can't unlock that.", "Unlock what?")
verbs.New(["use", "start"], "You're not sure how to use that.")
verbs.New(["wait", "z"], "Time passes.")
verbs.New("wake", "You're not dreaming.")
verbs.New("wear", "You can't wear that.")

verbs.New(["fuck", "shit", "dammit", "bitch"], "(That was completely unnecessary.)")
verbs.New("lol", "(wut?)")
verbs.New(["brb", "afk"], "(k, i'll wait)")
verbs.New("xyzzy", "There's a puff of orange smoke, and for a moment you think that something amazing is about to take place. But nothing happens. As the smoke clears, you find that you haven't moved an inch.")
verbs.New("cry", "You wimper softly.")
verbs.New(["hello", "hi"], "(Well, hello to you, too.)")
verbs.New("sing", "What, and strain your vocals chords? I don't think so.")
verbs.New(["smile", "whistle"], "Already your disposition is better.")
verbs.New(["yell", "scream"], "There's no response.")
verbs.New("follow", "You can't follow that.")
verbs.New("poop", "(Yeah, I don't think so.)")

verbs.New("awesome", "(Yes, yes it is.)")
verbs.New("bastard", "(Hey, I'm doing what I can, here.)")
verbs.New("bye", "(What, you're leaving already?)")
verbs.New("drown", "(But you have so much to live for!)")
verbs.New(["how", "why", "what", "die", "cry", "where"], "(If you're having trouble, try typing 'help'.)")
verbs.New("nevermind", "(I didn't really want to help you anyway.)")
verbs.New(["okay", "ok", "sure"], "(Nice to know you agree.)")
verbs.New("stay", "(I'd like to, I really would. We should probably get back to the game, though.)")
verbs.New(["yes", "no"], "I'm not sure what you're responding to.")

items.New("me", ["myself", "self"])
Item("me").Location("startroom")
Item("me").Description("short", "you")
Item("me").Description("long", "It's you. If you have a mirror handy, you could just look at yourself in real life.\n{scripts.ShowInventory()}")
Item("me").isContainer = True

items.New("all")
Item("all").Location("me")

locations.New("null")